name: Crunchyroll Calendar Tracker

on:
  schedule:
    - cron: '0 */4 * * *' # Se ejecuta cada 12 horas
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt
        
    - name: Ejecutar Scraper
      run: python scraper.py
      
    - name: Guardar cambios (RSS y base de datos)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Esto crea los archivos en blanco si el bot no los ha generado
        touch history.json feed.xml 
        
        git add feed.xml history.json
        git commit -m "Actualización del calendario de estrenos" || exit 0
        git push 
    - name: Ejecutar Scraper
      run: python scraper.py
      
    # Añade estas líneas para guardar el HTML de debug
    - name: Subir HTML de debug
      uses: actions/upload-artifact@v4
      with:
        name: crunchyroll-debug-html
        path: debug_crunchyroll.html
      
    - name: Guardar cambios (RSS y base de datos)
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        touch history.json feed.xml 
        git add feed.xml history.json
        git commit -m "Actualización del calendario de estrenos" || exit 0
        git push    
